<?php
  require_once("code_insert_redis_cut.php");
  	//redis_write_departments();
 	//redis_read_departments();
 	// redis_write_dept_emp();
  //redis_read_dept_emp();
  //redis_write_dept_manager();
// redis_read_dept_manager();
 // redis_write_employees();
  //redis_read_employees();
//redis_write_salaries();
  //redis_write_pipeline_salaries();
 // redis_write_pipeline_2_salaries();
 //redis_read_salaries();
 
 // redis_write_titles();
  //redis_read_titles();
  //read_redis_select_command_1();
   //read_redis_pipeline_select_command_1();
 //redis_join_1_version1();
 // redis_join_1_version2();
  //redis_join_1_pipeline_version1();
 //redis_join_1_pipeline_version2();
  //redis_single_entity_3();
  //redis_single_pipeline_entity_3();
  //redis_join_2();
 //redis_join_pipeline_2();
  //redis_join_3();
  //redis_join_pipeline_3();
  //redis_join_4();
 // redis_join_pipeline_4();
  //redis_subquery_1();
  //redis_subquery_1_pipeline();
  //redis_subquery_2();
//  redis_subquery_2_pipeline();
  //update_salary();
  //update_salary_pipeline();
// redis_write_pipeline_salaries();
  //redis_read_pipeline_salaries();
 //redis_delete();
 // flushall();
  //redis_delete_pipeline();
  //update_by_condition_1();
  //update_by_condition_1_pipeline();
  //redis_read_departments();
  //update_by_condition_2();
  //update_by_condition_2_pipeline();
  //redis_write_salaries();
  //redis_read_salaries();
  //delete_condition_1();
  //delete_condition_1_pipeline();
  //delete_condition_2();
  delete_condition_2_pipeline();
?>